name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - run: npm install 
      - run: npm run build