name: Build
on:
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - run: npm install 
      - run: npm run build
